### ISSUE TITLE
Can make a hapi.js integration too?

### ISSUE THREAD

**Issue by jorgecuesta** [tesfaldet/mongoose-opt-paginate#4]
Hi guys, doing a research on google I found your work and look really nice (grats!) I be working with Hapi.js and is a really nice Framework, maybe you can do an extra to support it?
Regards,

**Comment by tesfaldet** [comment]
Hey Jorge,

Thanks! There are still some things I'd like to work on, such as having optimized pagination work for date fields. I looked into Hapi.js and it certainly looks nice, however, I currently wouldn't have the time to start working on a Hapi.js implementation (in school right now!). Feel free to fork the project and make your own though!

**Comment by jorgecuesta** [comment]
Hi @tesfaldet I create Hapi.js version forked from you and make reference to you and your great job!
https://www.npmjs.com/package/hapi-mongoose-opt-paginate
Regards
